### ISSUE TITLE
Enable using day{day_number}.txt for aoc_complete!

### ISSUE THREAD

**Issue by EmNudge** [Ben-Lichtman/aoc_driver#1]
some external tools, like `cargo_aoc` will pull input into `input/{year_num}/day{day_num}.txt` instead of `input/{year_num}/{day_num}.txt`. Having the aoc_complete macro check for both before deciding there isn't any input might be beneficial.

**Comment by Ben-Lichtman** [comment]
This sounds like a good idea. I may work on this on the weekend to improve the ergonomics

**Comment by Ben-Lichtman** [comment]
The new version will default to day{n}.txt because I agree that it looks nicer
